### ISSUE TITLE
PTC Heater Requires Using `direct5T` Test

### ISSUE THREAD

**Issue by Dlloydev** [Dlloydev/sTune#10]
If running sTune and using a PTC heater, the much quicker `directIP` test appears to produce good results for everything except for its ability to accurately determine PV max ... this also results in process gain and Kp being inaccurate (process gain too low, Kp too high).

Presently I'm using a thermal calculation to get PV Max which doesn't account for the positive temperature coefficient of the PTC, so I'll need to investigate. I may need to add a new `IP` test mode for PTC because the `IP` test is just so fast (240 sec vs 1122 sec) and so close to being ready for PTC testing to ignore. See comparison in image below:

![image](https://user-images.githubusercontent.com/63488701/152655010-2745c4d4-f307-4b01-aae0-2367645358a8.png)

**Comment by geleos27** [comment]
Will this also affect on other type of heaters with even bigger dead time and inertia?

**Comment by Dlloydev** [comment]
Thermal type heaters should should be OK with using the `directIP` test.

Note that the software does a check to see how controllable the process is (Tau / Dead Time). If you suspect any issue with the `directIP` results, then try running `direct5T` to compare results.

**Comment by Dlloydev** [comment]
Resolved in sTune 2.4.0
