### ISSUE TITLE
Can't compile Autotune_PID_v1 example.

### ISSUE THREAD

**Issue by SinisterRj** [Dlloydev/sTune#6]
Trying to compile Autotune_PID_v1 example returns this error in Arduino IDE 1.8.15 and 2.0.0-beta12:

`sketch_jan18a:33:85: error: no matching function for call to 'sTune::sTune(double*, double*, sTune::TuningMethod, sTune::Action, sTune::SerialMode)'
 sTune tuner = sTune(&Input, &Output, tuner.Mixed_PID, tuner.directIP, tuner.printALL);
                                                                                     ^
In file included from E:\Testes Arduino\sTune\sketch_jan18a\sketch_jan18a.ino:6:0:
C:\Users\Rodrigo\Documents\Arduino\libraries\sTune\src/sTune.h:16:5: note: candidate: sTune::sTune(float*, float*, sTune::TuningMethod, sTune::Action, sTune::SerialMode)
     sTune(float *input, float *output, TuningMethod tuningMethod, Action action, SerialMode serialMode);
     ^~~~~
C:\Users\Rodrigo\Documents\Arduino\libraries\sTune\src/sTune.h:16:5: note:   no known conversion for argument 1 from 'double*' to 'float*'
C:\Users\Rodrigo\Documents\Arduino\libraries\sTune\src/sTune.h:15:5: note: candidate: sTune::sTune()
     sTune();
     ^~~~~
C:\Users\Rodrigo\Documents\Arduino\libraries\sTune\src/sTune.h:15:5: note:   candidate expects 0 arguments, 5 provided
C:\Users\Rodrigo\Documents\Arduino\libraries\sTune\src/sTune.h:5:7: note: candidate: constexpr sTune::sTune(const sTune&)
 class sTune {  // Inflection Point Autotuner
       ^~~~~
C:\Users\Rodrigo\Documents\Arduino\libraries\sTune\src/sTune.h:5:7: note:   candidate expects 1 argument, 5 provided
exit status 1
no matching function for call to 'sTune::sTune(double*, double*, sTune::TuningMethod, sTune::Action, sTune::SerialMode)'
`

**Comment by Dlloydev** [comment]
Whoops ... example fixed.
Thanks finding this. - dlloyd
